#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <service-prefix>"
  echo
  echo -e "Returns the list of IAM actions for a given service prefix."
  exit 1
fi

readonly service_prefix="$1"

curl --header 'Connection: keep-alive' \
     --header 'Pragma: no-cache' \
     --header 'Cache-Control: no-cache' \
     --header 'Accept: */*' \
     --header 'Referer: https://awspolicygen.s3.amazonaws.com/policygen.html' \
     --header 'Accept-Language: en-US,en;q=0.9' \
     --silent \
     --compressed \
     'https://awspolicygen.s3.amazonaws.com/js/policies.js' |
    cut -d= -f2 |
    jq -r '.serviceMap[] | .StringPrefix as $prefix | .Actions[] | "\($prefix):\(.)"' |
    sort |
    uniq | grep "${service_prefix}:" | awk '{print "\047" $1 "\047" "\054"}'
